package com.example.dairyproject;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.View;
import android.widget.Button;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Calendar;

public class Milk_details extends AppCompatActivity {
    DatePickerDialog.OnDateSetListener listener;
    TextView textView;
 String milkDate_id;
    EditText milking_cDate;
    EditText morning_cTotal;
    EditText afternoon_cTotal;
    EditText evening_cTotal;
    EditText total_cMilk;
    EditText milk_cNotes;
    Button save_Records;
DatabaseReference milkDbRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_milk_details);

    milking_cDate = findViewById(R.id.milking_date);
    morning_cTotal = findViewById(R.id.morning_total);
    afternoon_cTotal = findViewById(R.id.afternoon_total);
    evening_cTotal = findViewById(R.id.evening_total);
    total_cMilk = findViewById(R.id.milk_total);
    milk_cNotes = findViewById(R.id.Milk_notes_id);
    save_Records = findViewById(R.id.save_mButton);
    milkDbRef = FirebaseDatabase.getInstance().getReference().child("Milk_Details");



    // Add total in editTexts
        TextWatcher textWatcher = new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }
            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
            }
            @Override
            public void afterTextChanged(Editable s) {
                calculateTotal();

            }

            private void calculateTotal() {
                int morningValue = 0;
                int afternoonValue = 0;
                int eveningValue = 0;

                try {
                  morningValue = Integer.parseInt(morning_cTotal.getText().toString());
                  afternoonValue = Integer.parseInt(afternoon_cTotal.getText().toString());
                  eveningValue = Integer.parseInt(evening_cTotal.getText().toString());
                } catch (NumberFormatException e){
                    //  To handle invalid input if needed
                }
                int totalMilk = morningValue + afternoonValue + eveningValue;
                total_cMilk.setText(String.valueOf(totalMilk));

            }
        };
        morning_cTotal.addTextChangedListener(textWatcher);
        afternoon_cTotal.addTextChangedListener(textWatcher);
        evening_cTotal.addTextChangedListener(textWatcher);

        // save data
    save_Records.setOnClickListener(v -> {
            DatabaseReference new_milk_record = milkDbRef.push();
            String autoGeneratedId = new_milk_record.getKey();

            milkDate_id= autoGeneratedId;
            String milking_Date = milking_cDate.getText().toString();
           String morning_Total = morning_cTotal.getText().toString();
           String afternoon_Total = afternoon_cTotal.getText().toString();
           String evening_Total = evening_cTotal.getText().toString();
           String milk_Total = total_cMilk.getText().toString();
           String milk_Notes = milk_cNotes.getText().toString();

           Milk new_milkRec = new Milk(milkDate_id,milking_Date, morning_Total, afternoon_Total, evening_Total, milk_Total,milk_Notes);
          // milkDbRef.setValue(milk);
//            Toast.makeText(Milk_details.this, "Milk records updated successfully!!", Toast.LENGTH_SHORT).show();
//            Toolbox.navigateTo(Milk_details.this, Display_milk.class);
new_milk_record.setValue(new_milkRec, new DatabaseReference.CompletionListener() {
    @Override
    public void onComplete(@Nullable DatabaseError error, @NonNull DatabaseReference ref) {
        if(error != null){
            Toolbox.showToast(getApplicationContext(),error.getMessage());
        }else {
            // data was saved
            Toolbox.showToast(Milk_details.this,"Data saved successfully");
            Toolbox.navigateTo(getApplicationContext(), Display_milk.class);
        }
    }
});
    });

// Date picker dialog -------
        Calendar calendar = Calendar.getInstance();
        final int year = calendar.get(Calendar.YEAR);
        final int month = calendar.get(Calendar.MONTH);
        final int day = calendar.get(Calendar.DAY_OF_MONTH);
        milking_cDate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DatePickerDialog datePickerDialog = new DatePickerDialog(Milk_details.this, android.R.style.Theme_Holo_Light_Dialog_MinWidth, (DatePickerDialog.OnDateSetListener) listener,year,month,day);
                datePickerDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.BLUE));
                datePickerDialog.show();
            }
        });
        listener = new DatePickerDialog.OnDateSetListener(){
            public void onDateSet(DatePicker view, int year, int month, int dayOfMonth){
                month = month + 1;
                String date = dayOfMonth + "/" + month + "/" + year;
                milking_cDate.setText(date);
            }
        };
        // Make the keyboard input numbers
        morning_cTotal.setInputType(InputType.TYPE_CLASS_NUMBER);
        afternoon_cTotal.setInputType(InputType.TYPE_CLASS_NUMBER);
        evening_cTotal.setInputType(InputType.TYPE_CLASS_NUMBER);
        total_cMilk.setInputType(InputType.TYPE_CLASS_NUMBER);
    }
}