package com.example.dairyproject.Activities;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.DatePicker;
import android.widget.EditText;

import com.example.dairyproject.JavaClasses.Events;
import com.example.dairyproject.R;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Calendar;

public class AddEvents extends AppCompatActivity {

    EditText EventType;
    EditText cSymptoms;
    EditText cDiagnosis;
    EditText TechnicianName;
    Button Save_event;
    EditText eventNotes;
    String EventId = " ";
    DatabaseReference eventsDbRef;
    EditText EventDate;
    private DatePickerDialog.OnDateSetListener listener;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_events);

        EventDate = findViewById(R.id.event_dateid);
         EventType = findViewById(R.id.event_typeid);
         cSymptoms = findViewById(R.id.symptoms_id);
         cDiagnosis = findViewById(R.id.diagnosis_id);
         TechnicianName = findViewById(R.id.technician_id);
        eventNotes = findViewById(R.id.events_notes_id);
        Save_event = findViewById(R.id.save_eventButton);

        eventsDbRef = FirebaseDatabase.getInstance().getReference("Events_Details");

        Save_event.setOnClickListener(v -> {
            DatabaseReference new_new_event = eventsDbRef.push();
            String autoGeneratedId = new_new_event.getKey();

            EventId = autoGeneratedId;

            String EvDate = EventDate.getText().toString();
            String EvType = EventType.getText().toString();
            String EvSymptoms = cSymptoms.getText().toString();
            String EvDiagnosis = cDiagnosis.getText().toString();
            String EvTechnician = TechnicianName.getText().toString();
            String EvShortNotes = eventNotes.getText().toString();

            Events new_event = new Events(EventId,EvDate,EvType,EvSymptoms,EvDiagnosis,EvTechnician,EvShortNotes);
            new_new_event.setValue(new_event, new DatabaseReference.CompletionListener() {
                @Override
                public void onComplete(@Nullable DatabaseError error, @NonNull DatabaseReference ref) {

                    if(error != null){
                        Toolbox.showToast(getApplicationContext(),error.getMessage());
                    }else {
                        // data was saved
                        Toolbox.showToast(AddEvents.this,"Data saved successfully");
                        Toolbox.navigateTo(getApplicationContext(), ViewEventsActivity.class);
                    }
                }
            });

        });
        // Date picker dialog -------
        Calendar calendar = Calendar.getInstance();
        final int year = calendar.get(Calendar.YEAR);
        final int month = calendar.get(Calendar.MONTH);
        final int day = calendar.get(Calendar.DAY_OF_MONTH);
        EventDate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DatePickerDialog datePickerDialog = new DatePickerDialog(AddEvents.this, android.R.style.Theme_Holo_Light_Dialog_MinWidth, (DatePickerDialog.OnDateSetListener) listener,year,month,day);
                datePickerDialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.BLUE));
                datePickerDialog.show();
            }
        });
        listener = new DatePickerDialog.OnDateSetListener(){
            public void onDateSet(DatePicker view, int year, int month, int dayOfMonth){
                month = month + 1;
                String date = dayOfMonth + "/" + month + "/" + year;
                EventDate.setText(date);
            }
        };
    }
}